### ISSUE TITLE
Regular short rendering freezes

### ISSUE THREAD

**Issue by maringuu** [ifreund/river#103]
# Problem
The freezes occur seemingly randomly but regularly (about 3 times in the last 2 hours).
When the freeze occured I wasn't doing anything special. Just typing in neovim.
It unfreezes when switching VTs. (Confirmed now)
Since mouse inputs and keyboard inputs are processed correctly during the freeze I assume it is a rendering freeze.

# Logs
I don't have any debug logs yet and will paste them later.

# Possible solution
I have set `focus-follows-cursor` to `strict`. The focus is thus updated on every mouse movement.
Maybe some sort of queue is processed to slowly and the switching VTs took just long enough for it to be finished.
When it freezes again I'll wait for some time to confirm this.

**Comment by ifreund** [comment]
It's likely that the rendering freeze is due to river's system for atomic transactions which achieves frame perfection. As clients may sometimes fail to respond to our configure requests, this system has a timeout of 200ms, which at a guess is the exact length of your "short freezes".

A well behaved client will typically respond fast enough that no more that one or two frames are repeated, if any. However river could likely handle misbehaving clients better in whatever case you are hitting here.

**Comment by maringuu** [comment]
Cant reproduce anymore and since I didn't have time to get any logs I am closing this.
