### ISSUE TITLE
Is it possible to disbale borders on specific windows?

### ISSUE THREAD

**Issue by snakedye** [ifreund/river#157]
https://gofile.io/d/7Ngsxi

I use river but my fetch doesn't recognize it.

**Comment by Leon-Plickat** [comment]
You want to disable the borders, but that would be just a visual fix for two problems I see here.

* Those nwg launcher thingies are just regular windows. On Wayland, that simply is the wrong way to do desktop widgets. The layer shell would be more appropriate.

* You see the gtk client side decoration because your version of gtk uses a deprecated protocol to communicate decorations with the server (not sure if ifreunds fix for that has been merged yet in gtk). River does not support that protocol, only the newer one.


Back to your question, there is no way to disable the border of specific windows, but you can add the app-ids of those programs to the csd filter (`riverctl csd-filter-add <app-id>`), which will make them use client side decoration.

**Comment by snakedye** [comment]
>Those nwg launcher thingies are just regular windows. On Wayland, that simply is the wrong way to do desktop widgets. The layer shell would be more appropriate.

I also suspected this. I had the same issue on Sway initially but it has an option to disable borders, the dev must have patched it recently for Sway because I no longer need commands in my config file to make them launch properly. 

>You see the gtk client side decoration because your version of gtk uses a deprecated protocol to communicate decorations with the server

Would updating gtk fix that? I'm looking for gtk-git on yay and I don't find anything useful.

**Comment by Leon-Plickat** [comment]
> Would updating gtk fix that? I'm looking for gtk-git on yay and I don't find anything useful.

To quote myself: "not sure if ifreunds fix for that has been merged yet in gtk", so I don't know. :shrug:

**Comment by ifreund** [comment]
Not reviewed or merged yet: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/2191

**Comment by ifreund** [comment]
There doesn't seem to be anything actionable here
