### ISSUE TITLE
[Feature Request] different layouts for different tags

### ISSUE THREAD

**Issue by gspe** [ifreund/river#218]
Would be nice if river will add support for different layouts for different tags.
In my workflow I usually have a lot of windows opened, they are organised by type (for example browser) or by task in different tags/workspaces. It's natural that different tags have different layout, for example the tag where all the browser windows are is a monocle layout, the tag where I work with documents is a left layout, etc. So is very annoying that when I switch back and forth the tag layout is switched to something else. 

To support this request I can say that every tiling wm have support for different layouts for different tags/workspaces: 
- dwm has [pertag](https://dwm.suckless.org/patches/pertag/) patch
- dwl has per tag patch [dwl patchs](https://github.com/djpohly/dwl/wiki/Patches) --> https://github.com/djpohly/dwl/compare/master...Bonicgamer:pertag.patch
- awesomewm builtin
- i3 builtin
- swaywm builtin
- xmonad builtin
- ...

**Comment by Leon-Plickat** [comment]
**tags != workspaces**

Rivers tags are not totally separate contexts you switch between, like the workspaces in sway. They are just groups of windows. Windows can have multiple tags and on an output multiple tags can be active simultaneously. How do you imagine those cases should be handled? For reference, river supports up to 32 tags, meaning the amount of possible tag combinations is almost as large as the largest number that a 32 bit unsigned integer can hold (*almost* since river does not allows no tags to be active). In other words, per-tag layouts are a non-trivial problem.

Doing it inside the compositor is clearly the wrong approach. Here is how to do it the right way: Wait for #112, then write a layout that changes based on the currently active tags. If you open an issue, we might consider changing the layout protocol so that tag information is always send before layout demands, which will make this a bit easier.

**Comment by jedugsem** [comment]
i implemented it this afternoon but not for diffrent layouts but for values for rivertile so every tag has its own factor for example. currently it only works for 9 or i think less workspaces``

**Comment by jedugsem** [comment]
[rivertile-main.zig.txt](https://github.com/ifreund/river/files/6565425/rivertile-main.zig.txt)

**Comment by jedugsem** [comment]
replace rivertile/main.zig with it before complilation, obviosly you need to rename it first

**Comment by timsofteng** [comment]
Hello. Is it not implemented yet? Any plans?
River is cool but it's necessary feature to try to migrate to it from sway.

**Comment by Leon-Plickat** [comment]
@timsofteng Read my earlier comment in this thread and you know the answer.

**Comment by timsofteng** [comment]
> @timsofteng Read my earlier comment in this thread and you know the answer.

I've read but still don't understand how can I do it right now.
Image I change layout bin current tag with mod-shift-arrow.
How to prevent changing around all tags except current?

**Comment by ifreund** [comment]
The tags of the output are made available to the layout client in the protocol, which makes implementing this in a custom layout client very doable:
https://github.com/ifreund/river/blob/177b99c6e25f271e62a97caf6495379de70c0f88/protocol/river-layout-v2.xml#L127

There are no plans to add such a feature to rivertile or river itself.

**Comment by HeavyRain266** [comment]
I'm pretty sure kile client from wiki page does per tag layouts.

**Comment by jedugsem** [comment]
I uploaded a modified rivertile.zig above, using it it works perfectly

**Comment by AngelJumbo** [comment]
Guys I really admire your work and I love almost everything about river but without this I can't use this compositor and yeah I saw the kile thing but at this point I prefer to keep using dwm or even hack on dwl. Anyways ignore this pointless comment.
Ĝis la revido!

**Comment by Leon-Plickat** [comment]
>  but without this I can't use this composito

It is already possible, you just need a layout generator that supports it. Check out the wiki page, we have a list of layout generators there.

**Comment by AngelJumbo** [comment]
> > but without this I can't use this composito
> 
> Check out the wiki page, we have a list of layout generators there.
Yes I already did that but all I want is the default rivertale with some sort of per tag option, I mean I don't want to define layouts un lua or other weird sintax and I tried "kile" but it breaks everything when I mess with the gaps.

**Comment by NickHastings** [comment]
Try stacktile. It has the features you want and doesn't require any special configuration. Ask in IRC if you have questions.

Leon-Plickat won't explicitly suggest stacktile, since it is his project and doesn't do the whole self promotion thing.

**Comment by gozenka** [comment]
I think pertag should be the default too.

Yes, you can accomplish this via layout generators, but people would prefer to use the out-of-the-box rivertile if it has sane defaults, rather than using a community layout just for this basic functionality.

Stacktile looks awesome by the way, thanks @Leon-Plickat.

There might be people who prefer the current way, but I personally cannot think of a use-case or benefit to it. All dwm users I have seen until now applied the pertag patch; even if it is the only patch they use. It is like the default in practice.

Some concerns with relying on layout generators for this would be:
- It is an extra step, while keeping it simple and default would be preferrable.
- Worry about layout generators not being maintained as well as base river in the long-term.
- Getting a layout generator with a lot of extra features you do not need only to get pertag functionality does not feel good.

Essentially I believe almost all river users would prefer pertag functionality, and I think it is worth considering making it the default, and letting people do the other way around and get non-pertag functionality via layout generators if they wish, which I believe would be really rare.
