### ISSUE TITLE
question, what did you change?

### ISSUE THREAD

**Issue by KingTheGuy** [ifreund/river#234]
i use nvim, and ive noticed that in river the cursor movement is very smooth and in general seems really responsive,  compared to bspwm, and oddly sway.
how? what are the secrets ?

**Comment by sjtio** [comment]
could it be a difference in the key repeat rate that you're experiencing? I suppose river could have a higher default repeat rate than sway or Xorg/bspwm

you can change this in river by using riverctl set-repeat command, so maybe mess about with that, I'm sure sway and Xorg have equivalent options

**Comment by ifreund** [comment]
Compared to Xorg base window managers, river should do a much better job of maintaining frame perfection due to the double buffering in the wayland protocol and river's own atomic transaction system.

Compared to sway however river does not have any advantage that I know of aside from a smaller/simpler codebase and freedom from i3's design decisions. The biggest difference between river and sway currently is that river does not yet do damage tracking. However, this is not a deliberate design choice, I simply haven't had time to implement it yet.
