### ISSUE TITLE
Layershell surfaces can cause the compositor to crash

### ISSUE THREAD

**Issue by snakedye** [ifreund/river#245]
Surfaces that are too big or outside the display can cause river to crash. I suspect it might be due to the arbitrary geometry limit river imposes on the clients (you can't move a window beyond the screen). 

This can also be tied with this [issue](https://github.com/ifreund/river/issues/226) regarding mako. Basically river's implementation of layershell has issues.

**Comment by Leon-Plickat** [comment]
>  I suspect it might be due to the arbitrary geometry limit river imposes on the clients (you can't move a window beyond the screen).

This only affects XDG-Shell views and XWayland views, and only if those are moved manually. It does not affect layer shell surfaces and also not views arranged by layouts.

In my experience layer shell applications often do not check if their anchored layer surfaces are wider / higher than the output, which  can cause problems. Maybe your issues are related to this.

**Comment by snakedye** [comment]
> In my experience layer shell applications often do not check if their anchored layer surfaces are wider / higher than the output

That's something I patch on my end but from my experience with other compositors, namely Sway and Wayfire, River is the only one that crashes due to this.

>allowing us to straight up ignore the edge-case of users moving windows off an output or even worse from one to another.

What's the difference between a window being dragged outside the screen and a layout generator making it spawn there?

**Comment by Leon-Plickat** [comment]
>  What's the difference between a window being dragged outside the screen and a layout generator making it spawn there?

On the technical side absolutely nothing, other than one being tied to direct user interactions, the other to the layout generator.

It is more about UX: When I implemented manually moving and resizing windows I chose to not allow users to move/resize windows out of the output for two reasons.

* When you can **manually** move windows off screen, users expect that they can also **manually** move windows between outputs. However river does not implement that. That may be implemented in the future, or maybe not, but not allowing windows to be moved off screen even if another monitor is right there neatly hides this.
* I never liked that other desktops allow users to do that. Why would you allow users to manually move windows completely off screen? If I tell sway to move a floating window out of the screen, it happily does so and the window is effectively lost. That makes no sense. There needs to be a limit how far you can move the window out of the output, and I chose rivers limit to be "not at all".

I don't think those point are a concern for layout generators though, so I left this out when I worked on the layout protocol. Maybe river will have that in the future, maybe not.

**Comment by snakedye** [comment]
> Why would you allow users to manually move windows completely off screen?

You wouldn't move a window entirely outside of screen. If you don't want to resize a window and just make space for another one or move it on the side, you drag it slightly outside the display.

Sway for example let's you drag a window until the cursor is at the edge of the screen ensuring that you would always be able to grab it back if you need it.

> but not allowing windows to be moved off screen even if another monitor is right there neatly hides this.

I don't think so. It makes the desktop area feel small especially when you have large windows. Ultimately it just removes what a user expect be a normal feature. When a layout generator spawn a window outside of the screen geometry, you're left even more confused because it's something that makes more sense on floating windows than on tiled ones.

**Comment by Leon-Plickat** [comment]
> You wouldn't move a window entirely outside of screen.

Well that is exactly my point. There needs to be some limit. Some point where you can drag the window out no further. That is inherently arbitrary. And I chose that limit to be right there so that no part of the window can leave the output.

River gives you 32 tags. If your desktop ever becomes cluttered, just use a few more of them. That is way more idiomatic than moving windows off-screen. Floating windows are not intended to deal with clutter. To be honest, I see this as a non-issue, especially since floating windows can hide behind tiled windows.

> Sway for example let's you drag a window until the cursor is at the edge of the screen ensuring that you would always be able to grab it back if you need it.

Relying on the pointer to stay within the output bounds is a hack. Sway still allows you to move the window completely out of the screen if you do it with keybinds. That should not be possible. So there needs to be a limit, hence my argument above.

> It makes the desktop area feel small especially when you have large windows.

Does the desktop also feel small when you tile those large windows? Because rivertile also keeps all windows neatly within the bounds of the output. Same thing.

> Ultimately it just removes what a user expect be a normal feature. 

I can't speak for river as a project, but I for myself consider "what a user expects to be a normal feature" to be completely irrelevant when writing code. It is not my fault that they expect stuff to be "normal". I want to write good software, not "normal" software.

Ultimately almost everything about river is abnormal. Or do you consider tiling window management normal? Or window decorations that are just a plain border? Or a desktop that does not come with a bar with a task switcher?

If we cared about being normal, river would be a clone of the windows desktop, written in gtk and configured with dconf.

> When a layout generator spawn a window outside of the screen geometry, you're left even more confused because it's something that makes more sense on floating windows than on tiled ones.

I'd rather add this constraint to layouts as well then to remove it from manual movement / resizing.

---

I am strongly in favour of the current behaviour. But ultimately it is not my call, so if you think it should change, ask @ifreund

**Comment by snakedye** [comment]
> Sway still allows you to move the window completely out of the screen if you do it with keybinds.

I'm not claiming that what Sway does is also perfect and I understand the reasoning why there should be a limit but my initial complaint regarding the boundary was that the behaviour was inconsistent, didn't eliminate the edge cases where a window could be positioned outside the output (because the layout generator is exempt from it). 

On top of that it was unusual or going against the expectation of a user. Whether being unusual is good or bad is another debate but I think there's still something to take from what others do.

> I'd rather add this constraint to layouts as well then to remove it from manual movement / resizing.

That's fair but I think defining a limit there also increases the chances (depending on how it's implemented) the compositor crashes when an incorrect view is pushed. Which kinda comes back to the original point of this issue. That river is quick to crash on user errors that shouldn't be fatal imo and Layer shell was an exemple.

**Comment by Leon-Plickat** [comment]
On Thu Mar 25, 2021 at 5:54 PM CET, snakedye wrote:
> That river is quick to crash on user errors that
> shouldn't be fatal imo and Layer shell was an exemple.

The layer shell implementation is not related to view constraints. We
went a bit off-track here.

I am pretty confident in my original idea that this is because the
surface has anchors on two opposite sites, which per protocol means
the surface /must/ have the same width or height of the output, but is
in fact larger than that, probably breaking a few assumptions of the
layer shell implementation code. I am not surprised by this,
considering that this error is only implied in the protocol, but not
actually spelled out as far as I remember.

Do you have an error trace when river crashes? Can you reliably
recreate the crash? That would be most helpful.

I will try writing a layer shell test application that commits wrong
buffer sizes on purpose, to see if that crashes river, but that'll
have to wait a few days since I don't have a lot of time currently.


Friendly greetings,
Leon Henrik Plickat

**Comment by Leon-Plickat** [comment]
Can reproduce.

My initial suspicion was correct, it is an integer overflow due river not expecting a surface size larger than the output. More specifically, it is caused by `zwlr_layer_surface_v1_set_size()`; Attaching too large buffers is correctly handled though.

Abbreviated log below.

```
[...]
debug: (layer_shell) send configure, 2558 x 31
debug: (layer_shell) send configure, 1278 x 31
debug: (layer_shell) send configure, 1278 x 31
00:00:12.512 [types/wlr_surface.c:666] New wlr_surface 0x23bd470 (res 0x23bd820)
00:00:12.513 [types/wlr_layer_shell_v1.c:458] new layer_surface 0x23b3e20 (res 0x23b3f80)
00:00:12.513 [types/wlr_surface.c:666] New wlr_surface 0x240dc90 (res 0x240e040)
debug: (server) New layer surface: namespace wlclock, layer Layer.overlay, anchor Anchor{ .top = false, .bottom = true, .left = true, .right = true, ._paddding4 = false, ._paddding5 = false, ._paddding6 = false, ._paddding7 = false, ._paddding8 = false, ._paddding9 = false, ._paddding10 = false, ._paddding11 = false, ._paddding12 = false, ._paddding13 = false, ._paddding14 = false, ._paddding15 = false, ._paddding16 = false, ._paddding17 = false, ._paddding18 = false, ._paddding19 = false, ._paddding20 = false, ._paddding21 = false, ._paddding22 = false, ._paddding23 = false, ._paddding24 = false, ._paddding25 = false, ._paddding26 = false, ._paddding27 = false, ._paddding28 = false, ._paddding29 = false, ._paddding30 = false, ._paddding31 = false }, size 50000x50000, margin (0,0,0,0), exclusive_zone 0
debug: (layer_shell) send configure, 1278 x 31
integer overflow
/home/leon/Projects/Contributing/river/river/Output.zig:428:64: 0x24b71a in Output.arrangeLayer (river)
            new_box.y = bounds.y + @intCast(i32, bounds.height - current_state.desired_height -
                                                               ^
/home/leon/Projects/Contributing/river/river/Output.zig:342:43: 0x22fab9 in Output.arrangeLayers (river)
    for (layers) |layer| self.arrangeLayer(self.getLayer(layer).*, full_box, &usable_box, false);
                                          ^
/home/leon/Projects/Contributing/river/river/LayerSurface.zig:60:25: 0x227915 in LayerSurface.init (river)
    output.arrangeLayers();
                        ^
/home/leon/Projects/Contributing/river/river/Server.zig:229:19: 0x227c6d in .wayland.wayland_server_core.struct:490:17.wrapper (river)
    node.data.init(output, wlr_layer_surface);
                  ^
../util/signal.c:29:3: 0x7f6550e85c66 in wlr_signal_emit_safe (../util/signal.c)
../types/wlr_layer_shell_v1.c:364:3: 0x7f6550e6a724 in layer_surface_role_commit (../types/wlr_layer_shell_v1.c)
../types/wlr_surface.c:427:3: 0x7f6550e7cbf0 in surface_commit_pending (../types/wlr_surface.c)
../types/wlr_surface.c:499:3: 0x7f6550e7ce6e in surface_commit (../types/wlr_surface.c)
???:?:?: 0x7f6550ab7acc in ??? (???)
Panicked during a panic. Aborting.
ERROR: wl_display_flush: Broken pipe
Abgebrochen (Speicherabzug geschrieben)
```

**Comment by Leon-Plickat** [comment]
Turns out rivers layer shell implementations has quite a lot of subtractions of unsigned integers that could explode when layer shell clients submit too large values...

**Comment by Leon-Plickat** [comment]
@snakedye can you test with #248 ?

**Comment by snakedye** [comment]
> @snakedye can you test with #248 ?

Yes, it no longer crashes now :+1:
