### ISSUE TITLE
Cant Start River through tty

### ISSUE THREAD

**Issue by Preyt** [ifreund/river#265]
I am unable to start River through tty. I am using the Aur package. I get these type of errors when I attempt to start river:

- [libseat] [libseat/backend/seatd.c:78] could not connect to socket /run/seatd.sock : No such file or directory
- The above error is repeated for logind

since no back end was able to open a seat , river cannot be started. How do i resolve this issue?

**Comment by wrkzk** [comment]
I initially had this problem as well when using the AUR package. I solved it by enabling the elogind service. Verify that either seatd or logind is running before starting river.

**Comment by Preyt** [comment]
> I initially had this problem as well when using the AUR package. I solved it by enabling the elogind service. Verify that either seatd or logind is running before starting river.

How do I start seatd?

**Comment by wrkzk** [comment]
Assuming you have `seatd` installed and are using systemd, try running `sudo systemctl enable seatd.service`.

**Comment by ifreund** [comment]
Closing as this appears to be a configuration issue. Even if it's not, the bug is with wlroots/libseat not river.

**Comment by miyl** [comment]
Is that a difference between Sway and River, that River is dependent on libseat? Because I'm getting a similar issue with `seatd` trying to launch it from a TTY directly (through my shell's config file), while Sway launches just fine in the same way.

`seatd` is not running, but it seems starting it doesn't make a difference.
