### ISSUE TITLE
Hide a window?

### ISSUE THREAD

**Issue by tmpm697** [ifreund/river#322]
Sometime I want to hide a window by press combined keys like `control-alt-h`.

I can achieve in Xorg via using `wmutils` to hide an active window under cursor, but how to on wayland/river?

**Comment by Leon-Plickat** [comment]
By changing the focused tags or the tags of the window.

**Comment by tmpm697** [comment]
I mean windows in the same tags, i.g: I have two terminal window in a tag and I want a window disappears from screen.

**Comment by thallium** [comment]
I want this feature too, more specifically, minimize a window.

**Comment by Leon-Plickat** [comment]
This is unlikely to ever be added to river.

It just does not fit into how rivers window management works.

**Comment by Leon-Plickat** [comment]
Any desktop having tags / virtual desktops / workspaces does not need window hiding if used correctly.

**Comment by thallium** [comment]
but isn't that now quite easy to use? I would like to know if you have a good solution for that.

**Comment by Leon-Plickat** [comment]
@thallium river already has a way to set which windows are shown and which are hidden: Tags. If you make use of the fact that windows and outputs can have more than one active tag it is pretty simple to re-configure the current set of visible windows. Take a look at the scratchpad article in the wiki to see an example of how flexible rivers tag system is.

Adding window minimization add another parameter for window management, adding considerably complexity to code and usage, while offering nothing that couldn't already be achieved otherwise.

Want to hide a window? Move it to an in-active tag. Want to show the window again? Toggle that tag on the output. Want to hide it again? Toggle that tag on the output again.

**Comment by novakne** [comment]
> And ignoring the technical aspect, the concepts of "minimized" and "maximized" windows just don't fit into rivers window management paradigm.

Don't fit tiling windows management in general tbh

**Comment by tmpm697** [comment]
@novakne : So in tiling window concepts in general, all windows must be visible on screen? that's weird imo.

**Comment by Leon-Plickat** [comment]
@tmpm697 no, not all windows. It is just that the mechanism determining which windows are visible is a different one.

**Comment by tmpm697** [comment]
It seems a rare case but if I have setup only one tag/workspace and have all windows at full (I set that or patch), if we have like >3 full windows at a time, then we need to hide some.
