### ISSUE TITLE
Some feedback and issues with own workflow

### ISSUE THREAD

**Issue by Meister1593** [ifreund/river#410]
Hello, i'm trying out river and it seems quite promising from what i've seen (i didn't quite like sway), but had some issues with certain things:
1. I can't move window using mouse into another output, is it intentional or just not yet implemented?
2. How... can i resize window without dropping it out into floating move (like resizing all other window in tag at the same time)? every time i try to resize - it just drops into floating. This includes resizing with mouse (and moving window with mouse)
3. Can i toggle tiling or floating for all window under tag?
4. Can i change tag under output without focusing on window under that output? (just by moving mouse onto desired output, and without loosing focus from previous window)

Small sidenote:
Before river, last tiling wm i used was awesomewm, so i'm adapting my workflow from it

**Comment by Meister1593** [comment]
Also i noticed that resizing with mouse happens only from right bottom corner
i think it may be better if it would happen from closest corner from where you started resizing?

**Comment by Meister1593** [comment]
One more thing, i noticed that apps that can't be resized less than some threshold are not considered into tiled sizes and new apps will just overlap it anyway

**Comment by ifreund** [comment]
> I can't move window using mouse into another output, is it intentional or just not yet implemented?

Intentional for now at least.

> How... can i resize window without dropping it out into floating move (like resizing all other window in tag at the same time)? every time i try to resize - it just drops into floating. This includes resizing with mouse (and moving window with mouse)

You can't resize windows in the layout with the mouse. Windows in the layout have their sizes determined entirely by the layout generator, which may provide some way to configure sizes at runtime. See for example the `rivertile(1)` man page and it's `main-ratio` command.

> Can i toggle tiling or floating for all window under tag?

Nope, not yet but this behavior should be easily scriptable eventually.

> Can i change tag under output without focusing on window under that output? (just by moving mouse onto desired output, and without loosing focus from previous window)

Also not currently possible, but should be scriptable eventually as river's protocols mature.

> Also i noticed that resizing with mouse happens only from right bottom corner
> i think it may be better if it would happen from closest corner from where you started resizing?

Not yet, but see #399

> One more thing, i noticed that apps that can't be resized less than some threshold (discord in my case, horizontally) are not considered into tiled sizes and new apps will just overlap it anyway

This is intentional, the only real alternative would be simply cropping such programs to fit in the area given to them by the layout generator.

I'm going to close this as this isn't really a bug report, hope river works well for you!
