### ISSUE TITLE
riverctl snap does not respect bars

### ISSUE THREAD

**Issue by ThreeFx** [ifreund/river#427]
Running `riverctl snap up` with a bar on top of the screen results in the following: 

Before

![image](https://user-images.githubusercontent.com/6503361/132483788-8ba519d2-c3c6-4a48-aaec-facf906ed081.png)

After

![image](https://user-images.githubusercontent.com/6503361/132483822-09550867-fc1d-4b18-9bcc-5ef74be54c06.png)

I'm not sure whether this is a bug or expected behaviour. I think that either of the below alternatives are more natural:

1. snapping to the top, _but_ overlaying the bar
2. snapping below the bar

Let me know what you think.

**Comment by Leon-Plickat** [comment]
It's not a bug in code, since it works exactly the way I wanted it to when I implemented snapping. However if you'd prefer snapping respect layer shell surfaces with exclusive zones, then that makes sense as well.

---

Whether a window appears above or below a bar depends on the bars layer. Put your bar on the `bottom` layer and it will be below windows.

**Comment by ThreeFx** [comment]
> Whether a window appears above or below a bar depends on the bars layer. Put your bar on the bottom layer and it will be below windows.

Ah that helps a lot. In that case I think the behaviour is fine - I have no strong feelings on this matter.
