### ISSUE TITLE
River leaks an event FD to child processes

### ISSUE THREAD

**Issue by dnkl** [ifreund/river#76]
River leaks an event FD to spawned child processes. This can be reproduced by e.g. spawning a new terminal and running `cd /proc/self/fd; ls -l`:

```sh
% ls -l /proc/self/fd
total 0
lrwx------ 1 daniel users 64  1 aug 09.17 0 -> /dev/pts/2
lrwx------ 1 daniel users 64  1 aug 09.17 1 -> /dev/pts/2
lrwx------ 1 daniel users 64  1 aug 09.17 12 -> /dev/dri/card0
lrwx------ 1 daniel users 64  1 aug 09.17 2 -> /dev/pts/2
lrwx------ 1 daniel users 64  1 aug 09.17 36 -> anon_inode:[eventfd]
```
(the open `/dev/dri/card0` is a i915 bug I think).

I'm guessing there's an event FD opened somewhere without `FD_CLOEXEC` set.

I'm new to zig, and failed to find where this FD is coming from. I guess it could be zig itself, and not river that opens it.

**Comment by dnkl** [comment]
Forgot... this can be reproduced with a minimal config:
```
#!/bin/sh

# Use the "logo" key as the primary modifier
mod="Mod4"

# Mod+Shift+Return to start an instance of alacritty
riverctl map normal $mod+Shift Return spawn foot

# Mod+Q to close the focused view
riverctl map normal $mod Q close

# Mod+E to exit river
riverctl map normal $mod E exit
```

**Comment by dnkl** [comment]
Potential cause: https://github.com/ziglang/zig/pull/3913

My own attempt at doing the same in foot (replacing `pipe` with `eventfd` to handle errors between `fork` and `exec`): https://codeberg.org/dnkl/foot/commit/027a8de6f547115fd90b8ee612fc616b61d5000c

Which I then immediately reverted as it didn't really work (reason in commit message): https://codeberg.org/dnkl/foot/commit/bae3244ec6344bf0d28a01fa06895b9ad2d6c293

**Comment by ifreund** [comment]
Thanks for discovering and investigating this, you were totally right about what's happening. Since `std.ChildProcess` is currently leaking an fd and does more than we really need, I went ahead and replaced it with a simple `fork`/`execve` for spawning the startup process in main (54b09c4ae949aebc986f724abab912e5cab0cc1e). It's currently still in use for running the layout generators, but as far as I can tell isn't causing any fd leakage in that use case. I will investigate more and write up a bug report for the Zig std, I think this is fixed for river's use-case at least though.

**Comment by dnkl** [comment]
> I think this is fixed for river's use-case at least though.

I can at least confirm there aren't any more fd leaks.

>I will investigate more and write up a bug report for the Zig std

Much appreciated! I didn't want to do that myself without a test case, and I would need some time to get familiar enough with zig to be able to pull that off :)
