### ISSUE TITLE
[Request] Win r/unixporn: Rounded, Kawase, Opacity

### ISSUE THREAD

**Issue by linkert** [ifreund/river#81]
Here in Waylandland everything is different. No ibaghwan picom fork.

Wayfire have all the effects as plugins(?) and I though what a neat implementation!

All who's in the game know that all that matters are rounded corners, dual kawase blur and window opacity (active/inactive). Most of it is eye-candy but some actually helps with sanity while using a tiling window compositor.

What I'm suggesting is some similar visual options, tools and effects implemented in a fashion not unlike Wayfire. Optional, modular. Maybe not even included - but available - some official, some user contributed. 

If you are able to pull-off rounded corners à squircle with [curvature continuity](https://99percentinvisible.org/article/circling-square-designing-squircles-instead-rounded-rectangles/), River will win the r/unixporn master race forever! Just imagine - *"[River]"* flooding the feed!

Sway-project is super clear on its feelings towards such additions - if i3 doesn't have it, sway doesn't get it. So our only hope for a bspwm/dwm-like experience served on a bed of rice is river

I imagine, knowing pretty much NULL within software development, that the base code for the most common effects have been done by the Wayfire people already and would not be crazy difficult to have working with river?

For 1.0? ;) 

Anyhow - love this project, love you - all the best!

Robin

**Comment by Leon-Plickat** [comment]
River already supports opacity. On Wayland, just as on X, the client, the window itself, must also support transparency (unless you do total server side transparency, which is not a sane solution, as it has problems such as the text also becoming transparent). Just set the opacity level in your applications and done. All Wayland native terminals I have heard of support that (ok, weston-terminal does not, but who uses that anyway).

As for blur and rounded corners: Not feasible as of now. That would require river to implement its own renderer. That is a bit far fetched considering we don't even have damage tracking yet.

Also, getting rounded corners right is kinda complex. And I am not talking about that "rounded corner vs that apple thingy" thing you linked, but stuff like anti-aliasing, getting the borders right, etc. Also, server side rounded corners would require river to draw over window contents. Deciding which surface should be cropped and where is far from trivial, since surfaces may very well be larger than the window part of a window (for example, think about windows drawing their own shadows, like GTK stuff). All a compositor can do is guess based on a limited amount of information it has about the client. Our best bet would be to tell the clients their windows are tiled (which river does already by default) and hope they limit out-of-window drawing. Server side rounded corners are an ugly hack at best. If you want round corners, look for applications which draw them themselves (there are some GTK themes that have all four corners rounded, although they have issue with scrolled elements).

**Comment by Leon-Plickat** [comment]
Admittedly I am a bit biased since I think client side decorations are a better idea than server side decorations, but the problems I mentioned exist nonetheless.

**Comment by appetrosyan** [comment]
I think that damage tracking might be a little far fetched. But also an absolute necessity. The issue here is that because of the way wayland is made, it may be easier to make wayfire into a tiling WM, rather than plug blur into river.

**Comment by Leon-Plickat** [comment]
> it may be easier to make wayfire into a tiling WM

FYI Wayfire already has a tiling plugin. It is not perfect (it replicates i3 like tiling and has no gaps) but it does work.

**Comment by ifreund** [comment]
@Leon-Plickat's assessment is fairly accurate. Transparency is already supported and client-side. Rounded corners are best done client side. Blur and other effect would sensibly be done server-side, but they are purely cosmetic and fall just about last in terms of priority. Even if someone put in the effort to implement a custom renderer and fancy effects in river tomorrow, I would not merge it as there is still significant foundational work to be done.  Perhaps in a year or so when river's core features and functionality has somewhat stabilized this could be revisited.

> I think that damage tracking might be a little far fetched. But also an absolute necessity. 

Damage tracking will absolutely be implemented in river. It's not really that difficult per se, just work that needs to be done.

> The issue here is that because of the way wayland is made, it may be easier to make wayfire into a tiling WM, rather than plug blur into river.

This would absolutely be my recommendation if you want eyecandy in your wayland compositor today. One could likely implement dynamic tiling as a wayfire plugin without too much trouble. Yes the compositor isn't designed around it as river is, but wayfire is really the only option when it comes to fancy visual effects on wayland currently.

**Comment by linkert** [comment]
> ... Blur and other effects would sensibly be done server-side, **but they are purely cosmetic and fall just about last in terms of priority.** ... Perhaps in a year or so when river's core features and functionality has somewhat stabilized this could be revisited.
>
> > The issue here is that because of the way wayland is made, it may be easier to make wayfire into a tiling WM, rather than plug blur into river.
> 
> This would absolutely be my recommendation if you want eyecandy in your wayland compositor today.

No hurry at all - I'm totaly fine with knowing that such features are not totally of the map. It should not be anything other than last in terms of priority.

Checked out wayfires kawase blur effect - yummy! But I'll stay on Sway for now - it's growing on me really thanks to @Leon-Plickat 's config on sourcehut, alot of sane use of variables ;) Thanks!

**Comment by ifreund** [comment]
There's nothing actionable here, closing to clean up the issue tracker.

**Comment by ExtinctAxolotl** [comment]
Any updates on the status of this feature?

**Comment by ifreund** [comment]
Nope.
